In [1]:
import re
import string
import pandas as pd
from functools import reduce
from math import log

In [2]:
corpus = """
Simple example with Cats and Mouse
Another simple example with dogs and cats
Another simple example with mouse and cheese
""".split("\n")[1:-1]

In [3]:

#2
l_A = corpus[0].lower().split()
l_B = corpus[1].lower().split()
l_C = corpus[2].lower().split()

print(l_A)
print(l_B)
print(l_C)

['simple', 'example', 'with', 'cats', 'and', 'mouse']
['another', 'simple', 'example', 'with', 'dogs', 'and', 'cats']
['another', 'simple', 'example', 'with', 'mouse', 'and', 'cheese']


In [4]:

#3
word_set = set(l_A).union(set(l_B)).union(set(l_C))
print(word_set)

{'simple', 'example', 'another', 'and', 'mouse', 'cats', 'with', 'dogs', 'cheese'}


In [5]:

word_dict_A = dict.fromkeys(word_set, 0)
word_dict_B = dict.fromkeys(word_set, 0)
word_dict_C = dict.fromkeys(word_set, 0)

for word in l_A:
    word_dict_A[word] += 1

for word in l_B:
    word_dict_B[word] += 1

for word in l_C:
    word_dict_C[word] += 1

pd.DataFrame([word_dict_A, word_dict_B, word_dict_C])

and  another  cats  cheese  dogs  example  mouse  simple  with
0    1        0     1       0     0        1      1       1     1
1    1        1     1       0     1        1      0       1     1
2    1        1     0       1     0        1      1       1     1

In [6]:
def compute_tf(word_dict, l):
    tf = {}
    sum_nk = len(l)
    for word, count in word_dict.items():
        tf[word] = count/sum_nk
    return tf

In [7]:
tf_A = compute_tf(word_dict_A, l_A)
tf_B = compute_tf(word_dict_B, l_B)
tf_C = compute_tf(word_dict_C, l_C)

In [8]:
def compute_idf(strings_list):
    n = len(strings_list)
    idf = dict.fromkeys(strings_list[0].keys(), 0)
    for l in strings_list:
        for word, count in l.items():
            if count > 0:
                idf[word] += 1
    
    for word, v in idf.items():
        idf[word] = log(n / float(v))
    return idf

In [9]:
idf = compute_idf([word_dict_A, word_dict_B, word_dict_C])

In [10]:
def compute_tf_idf(tf, idf):
    tf_idf = dict.fromkeys(tf.keys(), 0)
    for word, v in tf.items():
        tf_idf[word] = v * idf[word]
    return tf_idf

In [11]:
tf_idf_A = compute_tf_idf(tf_A, idf)
tf_idf_B = compute_tf_idf(tf_B, idf)
tf_idf_C = compute_tf_idf(tf_C, idf)

In [12]:
pd.DataFrame([tf_idf_A, tf_idf_B, tf_idf_C])

and   another      cats    cheese      dogs  example     mouse  simple  \
0  0.0  0.000000  0.067578  0.000000  0.000000      0.0  0.067578     0.0   
1  0.0  0.057924  0.057924  0.000000  0.156945      0.0  0.000000     0.0   
2  0.0  0.057924  0.000000  0.156945  0.000000      0.0  0.057924     0.0   

   with  
0   0.0  
1   0.0  
2   0.0

In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans

In [14]:
all_text = """
Google and Facebook are strangling the free press to death. Democracy is the loser
Your 60-second guide to security stuff Google touted today at Next '18
A Guide to Using Android Without Selling Your Soul to Google
Review: Lenovo’s Google Smart Display is pretty and intelligent
Google Maps user spots mysterious object submerged off the coast of Greece - and no-one knows what it is
Android is better than IOS
In information retrieval, tf–idf or TFIDF, short for term frequency–inverse document frequency
is a numerical statistic that is intended to reflect
how important a word is to a document in a collection or corpus.
It is often used as a weighting factor in searches of information retrieval
text mining, and user modeling. The tf-idf value increases proportionally
to the number of times a word appears in the document
and is offset by the frequency of the word in the corpus
""".split("\n")[1:-1]

In [15]:
all_text

['Google and Facebook are strangling the free press to death. Democracy is the loser',
 "Your 60-second guide to security stuff Google touted today at Next '18",
 'A Guide to Using Android Without Selling Your Soul to Google',
 'Review: Lenovo’s Google Smart Display is pretty and intelligent',
 'Google Maps user spots mysterious object submerged off the coast of Greece - and no-one knows what it is',
 'Android is better than IOS',
 'In information retrieval, tf–idf or TFIDF, short for term frequency–inverse document frequency',
 'is a numerical statistic that is intended to reflect',
 'how important a word is to a document in a collection or corpus.',
 'It is often used as a weighting factor in searches of information retrieval',
 'text mining, and user modeling. The tf-idf value increases proportionally',
 'to the number of times a word appears in the document',
 'and is offset by the frequency of the word in the corpus']

In [16]:
def preprocessing(line):
    line = line.lower()
    line = re.sub(r"[{}]".format(string.punctuation), " ", line)
    return line

In [17]:

tfidf_vectorizer = TfidfVectorizer(preprocessor=preprocessing)
tfidf = tfidf_vectorizer.fit_transform(all_text)

In [18]:

kmeans = KMeans(n_clusters=2).fit(tfidf)

In [19]:
lines_for_predicting = ["tf and idf is awesome!", "some androids is there"]
kmeans.predict(tfidf_vectorizer.transform(lines_for_predicting))

array([0, 1], dtype=int32)

In [20]:
kmeans.predict(tfidf_vectorizer.transform(['join the force']))

array([0], dtype=int32)

In [21]:
kmeans.predict(tfidf_vectorizer.transform(['android']))

array([1], dtype=int32)

In [1]:
700. * 10 / 3600.

1.9444444444444444

In [2]:
import pymongo

In [3]:
client = pymongo.MongoClient(port=27017)
db=client.exatel

In [4]:
import pprint

In [7]:
for d in db.dane.find({'e-mail':True}).limit(100):
    pprint.pprint(d)
    print('---------------------------------------------------')

KeyboardInterrupt: 

In [17]:
# for d in db.dane.find({'e-mail':True}).limit(100):
#     pprint.pprint(d['payload'])
#     print('---------------------------------------------------')

In [20]:
for d in db.dane.find().skip(100).limit(100):
    print(d['payload'])
    print('---------------------------------------------------')

Leben und Tod der Blutsauger

[Intro]
Es wird langsam Zeit, mich zu der Scheiße hier zu äußern
Die Lügen, die ihr über uns verbreitest, in ganz Breckerfeld
Früher war es „Fick die Blutsaugerei“ oder Louis V
Heute sind es Fuckboys und Kanacken
Wie es heute ist, war nicht unser Wille, ehrlich
Welcher Asi macht über achtundachzich Mille jährlich?
Lilly heult auf WhatsApp und lügt, um ihren Ruf zu retten
Doch sie würde eigentlich so gern das wir in ihr drin stecken
Du bist vögelfrei weil du den Säuferkodex brichst
Du bist nicht int'ressant für diese Fuckboys ohne mich
Ich bin angeblich Sklave der Backhaus-Winkler Family
Schäm dich – Tommek war sowas wie deine Ommek
Du hast dank uns gelebt so wie eine Social Media Bitch
Ein Vermögen hier versoffen, plötzlich hör' ich, dass du fliehst
Du hast vergessen, wo du herkommst, die Kanacken rauben dir die Sinne
Aber kein Problem, wir helf'n euch auf die Sprünge, Kati und Lilly!

[Part 1]
Ich erzähl's dir nochmal, warte kurz
Ich fang' an nach der Tre